/*
 * GUIStatistics.java
 *
 * Created on 25 de Maio de 2009, 11:00
 */

package protoGUIDevice;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.table.DefaultTableModel;
import protoStatisticsDevice.StDData;
import protoStatisticsDevice.StDDataTransmission;
import protoStatisticsDevice.StDStatistics;

/**
 *
 * @author  Rafael de Santiago
 */
public class GUIStatistics extends javax.swing.JFrame {
    
    
    private StDData stdst;
    /** Creates new form GUIStatistics */
    public GUIStatistics(StDData stdst) {

        
        this.stdst = stdst;
        initComponents();

    }
    
    /*
     * Refresh the JTable of Download
     */
    private void refreshDownloadGrid(){
        DefaultTableModel model = (DefaultTableModel) jtblDownload.getModel();
        
        model.setNumRows(0);
        jtblDownload.updateUI();
        
        
        for(StDDataTransmission data: this.stdst.getDownloads()){
            String row[] = new String[7];
            NumberFormat fm = new DecimalFormat("0.00");
            row[0] = data.getTitle();
            row[1] = data.getPeerID();
            row[2] = data.getMsgID();
            row[3] = fm.format(data.getProgress()) + "%";
            row[4] = data.getDownloaded()/1024.0 + " KB";
            row[5] = fm.format(data.getRate()/1024)+" KBps";
            row[6] = (data.getTimeElapsed().longValue()/1000)+"s";
            model.addRow(row);
        }
        jtblDownload.updateUI();
    }
    
    /*
     * Refresh the JTable of Download
     */
    private void refreshPeerConnectedGrid(){
        DefaultTableModel model = (DefaultTableModel) jtblPConnected.getModel();
        model.setNumRows(0);
        jtblPConnected.updateUI();
        
        for(String data: this.stdst.getPeersConnected()){
            String row[] = new String[1];
            row[0] = data;
            model.addRow(row);
        }
        jtblPConnected.updateUI();        
    }    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblDownload = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblPConnected = new javax.swing.JTable();

        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("LOP2Pb: Mediation Layer");
        jLabel2.setAutoscrolls(true);

        jButton1.setText("Refresh");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtblDownload.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Block", "PeerID", "MsgID", "Percentual", "Downloaded", "Rate", "Time Elapsed"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblDownload);

        jTabbedPane1.addTab("Downloads", jScrollPane1);

        jtblPConnected.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PeerId"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtblPConnected);

        jTabbedPane1.addTab("Peers Connected", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                .addGap(39, 39, 39))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:
        this.refreshDownloadGrid();
        this.refreshPeerConnectedGrid();
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIStatistics(null).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jtblDownload;
    private javax.swing.JTable jtblPConnected;
    // End of variables declaration//GEN-END:variables
    
}
